//User Actions Types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER = "SET_USER";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_USERS = "SET_USERS";

export const SET_REQUEST = "SET_REQUEST";
export const ADD_PENDING_REQUEST = "ADD_PENDING_REQUEST";
export const ADD_APPROVED_REQUEST = "ADD_APPROVED_REQUEST";
export const REMOVE_PENDING_REQUEST = "REMOVE_PENDING_REQUEST";
export const ADD_INCOMING_REQUEST = "ADD_INCOMING_REQUEST";
export const REMOVE_INCOMING_REQUEST = "REMOVE_INCOMING_REQUEST";
export const SET_PENDING_REQUESTS = "SET_PENDING_REQUESTS";
export const SET_APPROVED_REQUESTS = "SET_APPROVED_REQUESTS";
export const SET_INCOMING_REQUESTS = "SET_INCOMING_REQUESTS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_NOTIFICATION_ALERT = "SET_NOTIFICATION_ALERT";
export const ADD_REJECTED_REQUEST = "ADD_REJECTED_REQUEST";
export const SET_REJECTED_REQUESTS = "SET_REJECTED_REQUESTS";